### PR TITLE
Split readme.md into several parts.

### PR DESCRIPTION
**Pull request by havenchyk**
Hi @stefanjudis!

As discussed in the #107 #101, I've tried to split the readme.md into several. Feel free to add any comments and suggestions.

### CODE REVIEW

**Comment by stefanjudis** [comment]
@havenchyk Hmm for some reason I was thinking we're splitting into platforms... Let me think about this approach. :)

**Comment by havenchyk** [comment]
Hey @stefanjudis, what do you think?

**Comment by stefanjudis** [comment]
@havenchyk 

Ja in my opinion it would be better to split the readme files into target platform as it will become more and more complex when we include squirrel.

**Comment by havenchyk** [comment]
No problem, could you please provide some rxample of this separation? I'm not sure I understand the idea.

**Comment by havenchyk** [comment]
@stefanjudis ping

**Comment by stefanjudis** [comment]
```
Readme ( general information )
  |-- creating windows installer ( including troubleshooting for windows )
  |-- creating mac dmg ( including troubleshooting for mac )
  |-- "how we use it so far"
```

Does this make sense?

**Comment by havenchyk** [comment]
LGTM, I'll provide changes accordingly with this plan.

**Comment by stefanjudis** [comment]
@havenchyk any news here?

No pressure - but I can do it myself too. :)

**Comment by havenchyk** [comment]
@stefanjudis haven't chance to take a look so far. If you can, please do it :+1:

**Pull request closed without merging**
