### PR TITLE
A spike on a linux builder

### PR DESCRIPTION
**Pull request by krainboltgreene**
Most linux applications are packaged around tar.

### CODE REVIEW

**Comment by krainboltgreene** [comment]
Thoughts before I keep going?

**Comment by stefanjudis** [comment]
@krainboltgreene 

Ja so far - looking okay for me. 
Or are you looking for any specific feedback?

**Comment by krainboltgreene** [comment]
@stefanjudis I don't think anyone is, but I had a linux guru basically help me with my custom builder, so I'll use it here.

**Comment by stefanjudis** [comment]
:+1: then. :)

**Comment by krainboltgreene** [comment]
Renaming the branch apparently deletes the branch? Come on github :P

**Pull request closed without merging**
