### PR TITLE
Feature/linux dmg support

### PR DESCRIPTION
**Pull request by justinmchase**
Build darwin .dmg files from linux.

### CODE REVIEW

**Comment by stefanjudis** [comment]
@justinmchase Can you please fix the build. I'll have a look then. :bowtie:

**Comment by justinmchase** [comment]
Sorry, I think I didn't re-lint after I merged. Should be fixed now!

**Comment by justinmchase** [comment]
Ping! :facepunch: 

Just wanted to send a reminder that I fixed the lint errors.

**Comment by stefanjudis** [comment]
Jup, saw it. Will tackle it next week. :)

**Comment by stefanjudis** [comment]
hey hey.

Will make a `electron-builder` session tomorrow night.
I plan to push test coverage and also build a dummy project on travis as additional test.

Afterwards I plan to have a look at your PR and merge it, if working fine. :)

I'll keep you updated.

**Comment by justinmchase** [comment]
Cool. For reference here is the dummy project I was using to test this changeset:
https://github.com/EvolveLabs/electron-updater-sample

I put the scripts into `package.json`, to be run as `npm run release`. 

Let me know if there is anything I can do.

**Comment by LinusU** [comment]
Hi @justinmchase, I'm the author of `appdmg`. You don't need to write a temporary json-file, you can just pass in `basename: '/path/to/dir'` and `specification: { ... }`.

Also, the linux-stuff is very interesting. What exactly does it do? I'm guessing that genisoimage makes a `dmg` out of a directory.

Maybe we could build this straight into `appdmg`? Just making it work on Linux as well :tada: :balloon:

**Comment by LinusU** [comment]
As I understand it the linux version here dosen't generate nice background and sets icon size and positions? This would be fixed if we bake this into `appdmg` :+1:

**Comment by stefanjudis** [comment]
Okay, as @LinusU jumped it ( thanks for that :bowtie: ).

I'd hold this one. Putting the functionality into `appdmg` itself seems to be are more elegant solution for me.

What do you think guys?

**Comment by justinmchase** [comment]
I do think that the background images are there, we tested that I believe. If you think it fits best in a lower down package that seems fine to me.

**Comment by stefanjudis** [comment]
@justinmchase @LinusU 

I think I would be good to have this somewhere else ( in `appdmg` for example ). This reduces complexity here and offers more value for people using `appdmg` already.

Shouldn't be a big deal to add it over there? So that we keep this going?

**Comment by justinmchase** [comment]
@LinusU Can I leave it to you to migrate the useful code in this pullrequest to appdmg? I'm out of time on this for now.

**Comment by openam** [comment]
What's the status of this?

**Comment by stefanjudis** [comment]
Pending on @LinusU side it guess. I'm sure he's excepting help on that. :)

**Comment by havenchyk** [comment]
@stefanjudis what's the status? What's need to be done here?

**Comment by stefanjudis** [comment]
> As I understand it the linux version here dosen't generate nice background and sets icon size and positions? This would be fixed if we bake this into appdmg...

Status was to bring it into appdmg itself - as it's the place for it. :)

**Comment by LinusU** [comment]
It might be so easy that a patch to appdmg to use `genisoimage` on linux would be all that's needed

**Comment by havenchyk** [comment]
@LinusU you can create an issue in your repository and describe what should be done and make the issue with a tag "help wanted", I will be glad to help you.

**Pull request closed without merging**
