### PR TITLE
Updates installer template to provide option of performing a portable install or an install to appropriate program files directory depending on architecture

### PR DESCRIPTION
**Pull request by joeferraro**
… refs #11

### CODE REVIEW

**Comment by stefanjudis** [comment]
@joeferraro 

Oh wow - that's a big PR.

Could you maybe explain briefly what you changed in detail.
There are a lot more changes as I can see. ;)

Will test it over the weekend. :)

And at the end squashing the commits would be nice.

Thanks a lot for that! :tada:

**Comment by joeferraro** [comment]
@stefanjudis hopefully the updated title helps. basically, this installer gives the user the option of performing either an install to program files or a portable install (anywhere on the drive). for the program files install, elevated (admin) privileges are requested.

**Comment by stefanjudis** [comment]
May I ask which windows versions you checked?

**Comment by joeferraro** [comment]
windows 8 32 bit, windows 8 64 bit

**Comment by stefanjudis** [comment]
All right! :+1: 

Let me make check on window 7 then over the weekend. 

As far as me being far away from being an expert in this, I'm happy to merge if this works fine. :bowtie: 

Feel free to ping me again - if nothing happened until monday. ;)

**Comment by joeferraro** [comment]
@stefanjudis I'm certainly no expert either. No rush on getting it pulled, I'm using my PR in the meantime

**Comment by stefanjudis** [comment]
No no - contributions have to go back, so I'm happy and will keep it in mind. ;)

**Comment by stefanjudis** [comment]
@joeferraro squashing commits might be nice though, because this PR includes a lot of them. :)

**Comment by joeferraro** [comment]
yeah no worries. what's the best way to do that? close this PR and open another?

**Comment by stefanjudis** [comment]
Or squash them locally and make a force push. Whatever you prefer. :)

**Comment by stefanjudis** [comment]
@joeferraro Any news on squashing or open another one? :blush:

**Comment by stefanjudis** [comment]
@joeferraro Do you plan to squash and resolve conflicts or can I close this one due to inactivity? :(

**Comment by joeferraro** [comment]
will re-submit

**Pull request closed without merging**
