### PR TITLE
Multilanguage, unicode and many pages

### PR DESCRIPTION
**Pull request by ANTPro**
Added multilanguage, unicode and many pages to installer template
Added unicode

Use NSIS 3.0 for build (for unicode support)

### CODE REVIEW

**Comment by stefanjudis** [comment]
Will check it next week. :) Feel free to ping after a while... :bowtie: 

My open source sunday time is over for today. ;)

**Comment by stefanjudis** [comment]
Hmm... as this is not available with `brew` yet - I think unfortunately I have to pass on this. :(

Or do you have any suggestions how to get it on mac. :)

This is what I get here:

```
> makensis --version                                                                      [20:46:16]
MakeNSIS v04-Oct-2015.cvs - Copyright 1995-2009 Contributors
See the file COPYING for license details.
Credits can be found in the Users Manual.

Usage:
  makensis [option | script.nsi | - [...]]
   options are:
    -CMDHELP item prints out help for 'item', or lists all commands
    -HDRINFO prints information about what options makensis was compiled with
    -LICENSE prints the makensis software license
    -VERSION prints the makensis version and exits
    -Px sets the compiler process priority, where x is 5=realtime,4=high,
        3=above normal,2=normal,1=below normal,0=idle
    -Vx verbosity where x is 4=all,3=no script,2=no info,1=no warnings,0=none
    -Ofile specifies a text file to log compiler output (default is stdout)
    -PAUSE pauses after execution
    -NOCONFIG disables inclusion of <path to makensis.exe>/nsisconf.nsh
    -NOCD disabled the current directory change to that of the .nsi file
    -Ddefine[=value] defines the symbol "define" for the script [to value]
    -Xscriptcmd executes scriptcmd in script (i.e. "-XOutFile poop.exe")
   parameters are processed by order (-Ddef ins.nsi != ins.nsi -Ddef)
   for script file name, you can use - to read from the standard input
   you can use a double-dash to end options processing: makensis -- -ins.nsi
FAIL: 1
```

And I think I'm up to date.

```
stefan @ stefan-mac: ~/Sites/blocky master (╯°□°)╯
> brew upgrade makensis                                                                   [20:47:29]
Error: makensis 2.46 already installed
```

**Comment by ANTPro** [comment]
I dont use mac. But NSIS 3.0 is beta. "brew" keep beta version?

**Comment by stefanjudis** [comment]
Ja - I'd wait with this one then until NSIS 3.0 is out of beta as it should make it easy to create installers and for mac users as this currently is not the case. :(

> "brew" keep beta version?

I don't understand.

**Comment by stefanjudis** [comment]
Closing until NSIS 3.0 is out...

-> we plan to move to Squirrel anyways soon'ish.

**Pull request closed without merging**
