### PR TITLE
Provides option of performing portable install or an install to appropriate program files directory depending on architecture

### LINKED ISSUE #11: App is installed under "Programs Files (x86)" on windows even when specifying --arch=x64
It appears to be getting the right binaries for electron but it seems to be putting it into the wrong location for some reason.

The code in the template is this: `InstallDir "$PROGRAMFILES\${APP_NAME}\"`

Which seems correct to me, so I'm not sure why this is happening. Filing this bug for posterity but I will investigate.

### LINKED ISSUE #36: Support ability to specify install location on Windows
This is helpful for folks who do not have admin access, for example

### PR DESCRIPTION
**Pull request by joeferraro**
fixes #36
fixes #11

### CODE REVIEW

**Comment by stefanjudis** [comment]
@joeferraro Hmm, shi.... 

Can we resolve merge conflicts once more? sorry about that.

**Comment by demetris-manikas** [comment]
Please check my comment on #36.
@joeferraro IMO the solution to #11 should be in a separate PR. Keeping PRs as simple as they can get makes the maintainer's life easier.

**Comment by stefanjudis** [comment]
> Keeping PRs as simple as they can get makes the maintainer's life easier.

:bowtie: :+1:

**Comment by Jaykah** [comment]
This is a great addition to electron-builder, can we please merge?

**Comment by stefanjudis** [comment]
As you see - can' merge. ;)

**Comment by develar** [comment]
We produce Squirrel.Windows installer now. Feel free to open new PR if issue still actual.

**Pull request closed without merging**
