### PR TITLE
Added support for windows  Unistall/DisplayVersion

### PR DESCRIPTION
**Pull request by demetris-manikas**
Very small patch to allow for version property in the nsi templates.
Let me know what you think.
Cheers

### CODE REVIEW

**Comment by stefanjudis** [comment]
Thanks. :bowtie: 

Fine for me - but it's missing the readme mention about that?

**Comment by demetris-manikas** [comment]
Updated the README.md but you probably have to rephrase it.
If version is not defined APP_VERSION is just an empty string

**Comment by stefanjudis** [comment]
@demetris-manikas 
Now that I'm thinking of it defaulting to version in package.json would be nice maybe?

**Comment by demetris-manikas** [comment]
I played with the idea but it needed more effort. Where is the package.json located? In my case it 's not even in the same dir as config.json. So things get complicated. Setting the path to the package.json would be a way. Should that be a global or a win param? These question made me go for the simple solution. Anyway it is very easy to produce a config.json containing the appropriate data.

**Comment by stefanjudis** [comment]
Okay - I see. Fair enough. :bowtie:

**Pull request merged**
