### PR TITLE
Updated "How we used it so far" part of README.md

### PR DESCRIPTION
**Pull request by Frondor**
Fix: changed `rm -rf` (which doesn't work on win7 x86) for `rimraf`.

### CODE REVIEW

**Comment by stefanjudis** [comment]
Thx. :bowtie: 

You might want to explain why rimraf is needed and point out how it should be installed?
There might be people not knowing why why it should be `rimraf` and not `rm -rf`...

**Comment by Frondor** [comment]
Sure, I'll try to reproduce the error and google the SO question that helped me because I can't remember it right now

**Comment by stefanjudis** [comment]
Nice, thanks a lot. :)

**Comment by Frondor** [comment]
Well, this seems most likely to be a windows problem. so I don't think that `clean` should use `rimraf`. You can reject this PR and I can make a new one.
The problem was that my build process was failing at this [line](https://i.gyazo.com/6cfa00154430a9751961dfcc689f2143.png) so after a google search I found [this issue](https://github.com/react-bootstrap/react-bootstrap/issues/491) which is solved by switching from `rm -rf` to `rimraf` :neckbeard:

**Comment by stefanjudis** [comment]
Ja I think a not somewhere for windows users is maybe enough, telling that they don't have the `rm -rf` command and should use the windows counterpart instead.

What do you think? :)

**Comment by Frondor** [comment]
I'm the noob here :laughing: 
The only problem with changing `clean:win` only is that `build` task won't work because `clean` and `clean:osx` are still using `rm -rf`.
As long as `rimraf` works for both `osx` and `win`, I think there won't be any problem since both commands do the same job.
p.s.: Didn't understand that about *"I think a not somewhere for windows users is maybe enough" * :/

**Comment by stefanjudis** [comment]
> I'm the noob here :laughing: 

no problem about that.

The problem is not the system you want to build for it's the system you want build on.

If you want to use `rm -rf` building anything it's not working.

Also `clean` is not part of `electron-builder` itself it's just a recommendation showing how we use it so far.

So a note like `If you want to clean you`re stuff and am on a windows machine please adjust rm -rf to use the windows command. Using libraries like rimraf may help to make it run on different environments`.

**Comment by Frondor** [comment]
Alright, seems good to me... Maybe in the future there should be two different points (bullets) inside "How we used it so far", one `package.json` for OSX, and another for windows. Because the build processes vary a bit between both OS.
Shall I make a new PR or you are fine?

**Comment by stefanjudis** [comment]
Jap go ahead then. :) Thx.

**Pull request closed without merging**
