### PR TITLE
Merge electron-complete-builder project into electron-builder

### PR DESCRIPTION
**Pull request by develar**
First phase of #138.

Tests passed:
 * Linux & OS X: https://travis-ci.org/develar/electron-builder/builds/109034851
 * Windows: https://ci.appveyor.com/project/develar/electron-builder/build/1.0.2

### CODE REVIEW

**Comment by stefanjudis** [comment]
@develar 

Ja looks okay for me... How do you plan to proceed then?

**Comment by develar** [comment]
> How do you plan to proceed then

Phase 2: Update docs and discuss (as part of the `update readme` pull request) what we want to do with the existing `electron-builder` API. 

* Drop it — I don't think it is an option. We should provide easy migration.
* Mark as deprecated and don't describe in the docs. I prefer this variant.
* Continue to maintain. Well, I don't find this API user-friendly.

Please note — the main problem here that `electron-complete-builder` doesn't build windows installer as `electron-builder` does. I think, we cannot build only squirrel installer because it is not appropriate for all, so, we should somehow add this functionality to new API (currently, `platform` accepts only win32 — should be a way to specify what kind of installer we want to get).

Phase 3: migrate existing tests to AVA.

**Comment by stefanjudis** [comment]
> Mark as deprecated and don't describe in the docs. I prefer this variant

Yeah sounds good but also including a nice migration guide.

> Please note — the main problem here that electron-complete-builder doesn't build windows installer as electron-builder does. I think, we cannot build only squirrel installer because it is not appropriate for all, so, we should somehow add this functionality to new API (currently, platform accepts only win32 — should be a way to specify what kind of installer we want to get)

Ja I'd keep `nsis` a short while and then simply drop it with a major release as Squirrel is the official recommended way to go.

Okay. :+1: 

I don't think I'm much help here as I don't have much time currently but yeah go ahead. :)

**Comment by develar** [comment]
Thanks, could you please add project to [Appveyor](https://www.appveyor.com) (it is required to run windows test and my pull request contains required `appveyor.yml`)?

**Comment by stefanjudis** [comment]
Done. 

https://ci.appveyor.com/project/stefanjudis/electron-builder

**Pull request merged**
