### PR TITLE
Stop process if already running

### PR DESCRIPTION
**Pull request by demetris-manikas**
If the application is already running the installation fails so just kill it. 
Maybe it would be a better solution to show some info and drop the installation but my knowledge about NSIS is still quite limited so as to implement this kind of behavior.

### CODE REVIEW

**Comment by stefanjudis** [comment]
> Is it possible to include a button on a dialog in case the user has something going before killing the running app?

That sounds great!!! :+1:

**Comment by demetris-manikas** [comment]
Any comments on changed implementation?

**Comment by stefanjudis** [comment]
Damn it. Sorry - I'll try to have a look at it tonight. :)

**Comment by stefanjudis** [comment]
@demetris-manikas Just tried it and it looks good to me.

Only thing:

Can we make the dialog a bit more explanatory?

screenshot 2015-12-09 21 00 17

I'm thinking of something like. 

"App is already running. This may affect the installation process. Please close the application."

And I think the cta's could be better.

Also it'd be great if "ignore" could be "close & continue" showing, that this will shut down the application.

What do you think?

**Comment by mkaz** [comment]
The solution I ended up going with was a  two button OK / CANCEL Message box.
Here's that code I used:

```
MessageBox MB_OKCANCEL|MB_ICONEXCLAMATION "${APP_NAME} is running. $\r$\nClick OK to close it and continue with install" /SD IDCANCEL IDOK doStopProcess
  	    Abort
    doStopProcess:
         DetailPrint "Closing running ${APP_NAME} ..."
         ${nsProcess::KillProcess} "${APP_NAME}.exe" $R0
         DetailPrint "Waiting for ${APP_NAME} to close."
         Sleep 2000
```

The result looks like:

stop-dialog-2

**Comment by stefanjudis** [comment]
@mkaz @demetris-manikas 

I have to say - I actually like @mkaz 's version more. 

What's do you two think?

**Comment by demetris-manikas** [comment]
It 's fine by me. I only wanted the installer not to hang when the app is already running.
Your call.

**Comment by demetris-manikas** [comment]
Incorporated changes proposed by mkaz.

**Comment by stefanjudis** [comment]
:+1: Looks good to me thanks!

**Pull request merged**
