### PR TITLE
fixed description

### PR DESCRIPTION
**Pull request by daB0bby**
Fixed description of icons

### CODE REVIEW

**Comment by stefanjudis** [comment]
Thanks - please fix merge conflicts. :)

**Comment by daB0bby** [comment]
How? :-)

**Comment by stefanjudis** [comment]
Merge the current master into your fork.

I think it's written just bellow at `This branch has conflicts that be resolved`. ;)

**Comment by daB0bby** [comment]
Here we go. Thanks!

**Pull request merged**
