### PR TITLE
change name macos to osx - fix #13

### LINKED ISSUE #13: Change 'macos' to 'osx'

### PR DESCRIPTION
**Pull request by radibit**

### CODE REVIEW

**Comment by stefanjudis** [comment]
Looks good! :+1: 

We can merge tomorrow then. :)

**Comment by stefanjudis** [comment]
hey hey.

Will make a electron-builder session tomorrow night.
I plan to push test coverage and also build a dummy project on travis as additional test.

Afterwards I plan to have a look at your PR and merge it, if working fine. :)

I'll keep you updated.

**Comment by radibit** [comment]
Thank you! I will be available if you need any assistance :smiley:

**Comment by stefanjudis** [comment]
Working fine. :)

**Comment by radibit** [comment]
Glad to hear that. Didn't have much time to test it properly :blush:

**Comment by stefanjudis** [comment]
All good. It's already out there. ;)
Am 18.06.2015 22:27 schrieb "Radimir Bitsov" <notifications@github.com>:

**Pull request merged**
